bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

jewelry_palace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('privacy/',
         TemplateView.as_view(template_name='privacy.html'),
         name='privacy'),
    path('terms/',
         TemplateView.as_view(template_name='terms.html'),
         name='terms'),
    path('about/',
         TemplateView.as_view(template_name='about.html'),
         name='about'),
    path('profiles/', include('profiles.urls')),
    path('faq/', include('faq.urls')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'jewelry_palace.views.handler404'

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>', views.product_detail, name='product_detail'),
    path('<int:product_id>/reviews/add/', views.add_review, name='add_review'),
    path(
        '<int:product_id>/reviews/<int:review_id>/edit/',
        views.edit_review,
        name='edit_review',
    ),
    path(
        '<int:product_id>/reviews/<int:review_id>/delete/',
        views.delete_review,
        name='delete_review'
    ),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>', views.edit_product, name='edit_product'),
    path(
        'delete/<int:product_id>', views.delete_product, name='delete_product'
        ),
    path('my-reviews/', views.my_reviews, name='user_reviews'),
]

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from django_countries.fields import CountryField
from products.models import Product
from profiles.models import UserProfile

# Create your models here.


class Order(models.Model):
    """"A model design to keep track of customers orders
    """
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(
        UserProfile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="orders",
    )
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=40, null=False, blank=False)
    country = CountryField(blank_label="Country *", null=False, blank=False)
    postcode = models.CharField(max_length=20, null=False, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    original_bag = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(
        max_length=254, null=False, blank=False, default='')

    def _generate_order_number(self):
        """
        Generate random and unique order number is uuid
        """
        return uuid.uuid4().hex[:12].upper()

    def update_total(self):
        """
        Upgrade grand total each time an item is added
        """
        self.order_total = self.lineitems.aggregate(Sum('lineitem_total'))[
            'lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = self.order_total * \
                settings.STANDARD_DELIVERY_PERCENTAGE / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it is not already set
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    """
    Model to display individual products attached to each order
    """

    order = models.ForeignKey(Order, null=False, blank=False,
                              on_delete=models.CASCADE,
                              related_name='lineitems')
    product = models.ForeignKey(Product, null=False, blank=False,
                                on_delete=models.CASCADE)
    quantity = models.IntegerField(null=False, blank=False, default=0)
    product_size = models.CharField(max_length=2, null=True, default=0)
    lineitem_total = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, blank=False,
        editable=False)

    def save(self, *args, **kwargs):
        """
        Override the orginal save method to set the line item
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=100)
    friendly_name = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    category = models.ForeignKey(
        'Category', null=True, blank=True, on_delete=models.SET_NULL)
    sku = models.CharField(
        max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(
        max_digits=6, decimal_places=2, null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.name


class Review(models.Model):
    """
    Models representing user review for products.
    """

    product = models.ForeignKey(Product,
                                on_delete=models.CASCADE,
                                related_name='reviews')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, null=True, blank=True)
    rating = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        null=True,
        blank=True
    )
    comment = models.TextField(null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date_added']

    def __str__(self):
        return f'Review for {self.product.name} by {self.user.username}'

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower

from .forms import ProductForm, ReviewForm
from .models import Product, Category, Review

# Create your views here.


def all_products(request):
    """A view to show all the products, including sorting and search queries"""

    products = Product.objects.all()
    query = None
    categories = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'drection' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
                products = products.order_by(sortkey)

            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(
                    request, "You didn't enter any search criteria!")
                return redirect(reverse('products'))

            queries = (Q(name__icontains=query) |
                       Q(description__icontains=query))
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_item': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """A view to show individual product details"""

    product = get_object_or_404(Product, pk=product_id)

    context = {
        'product': product,
    }

    return render(request, 'products/product_detail.html', context)


@login_required
def my_reviews(request):
    reviews = Review.objects.filter(user=request.user).select_related(
        'product')

    return render(request, 'products/user_reviews.html', {'reviews': reviews})


@login_required
def add_review(request, product_id):
    """
    A view to add a new review
    """

    product = get_object_or_404(Product, pk=product_id)
    user_review = product.reviews.filter(user=request.user).first()

    if user_review:
        messages.error(request,
                       'Looks like you have already reviewed this product. '
                       'Feel free to update it instead')
        return redirect(
            'edit_review', product_id=product.id, review_id=user_review.id)

    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.product = product

            review.save()
            print('review')
            messages.success(request,
                             'Your product review has been submitted.')
            return redirect(reverse('product_detail', args=[product_id]))
        else:
            messages.error(request,
                           'An error occured whilst saving your review')
    else:
        form = ReviewForm()

        template = 'products/add_review.html'
        context = {
            'product': product,
            'form': form,
        }

        return render(request, template, context)


@login_required
def edit_review(request, product_id, review_id):
    """Edit an existing review for a product by the logged-in user."""
    product = get_object_or_404(Product, pk=product_id)
    review = get_object_or_404(
        Review, pk=review_id, product=product, user=request.user)

    form = ReviewForm(request.POST or None, instance=review)

    if request.method == "POST" and form.is_valid():
        form.save()
        messages.success(request, "Your review has been updated successfully!")
        return redirect("product_detail", product_id=product.id)

    return render(request, "products/edit_review.html", {
        "form": form, "product": product, "review": review})


@login_required
def delete_review(request, product_id, review_id):
    """Delete a review if the logged-in user is the owner."""
    review = get_object_or_404(
        Review, pk=review_id, product_id=product_id, user=request.user)

    if request.method == "POST":
        review.delete()
        messages.success(request, "Your review has been deleted.")
        return redirect("product_detail", product_id=product_id)

    return render(
        request, "products/delete_review.html",
        {"review": review, "product": review.product})


def add_product(request):
    "add product to the store"
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to add product, \
                           Please ensure the form is valid.')
    else:
        form = ProductForm()

        template = 'products/add_product.html'
        context = {
            'form': form,
        }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """
    Edit a product in the store
    """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request,
                'Failed to update product. Please ensure the form is valid'
            )
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """
    Delete product from the app
    """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('products'))

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6 ">
                <hr>
                <h2 class="logo-font mb-4"><strong>Product Managment</strong></h2>
                <h5 class="text-muted">Add a Product</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6">
                <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                    <div class="text-right">
                        <a class="btn btn-outline-black rounded-0" href="{% url 'products' %}">Cancel</a>
                        <button class="btn btn-black rounded-0" type="submit">Add Product</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/add_review.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
{% endblock %}

{% block page_header %}
    <div class="container text-center py-4" style="height: 40vh;">
        <h2 class="logo-font mb-4">Write a Review for {{ product.name }}</h2>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <div class="card p-4 shadow-sm">
                    <h4 class="text-muted">Your Review</h4>
                    <form method="POST" id="review-form">
                        {% csrf_token %}

                        <!-- Review Title -->
                        <div class="form-group">
                            <label for="title_id" class="font-weight-bold">Review Title:</label>
                            {{ form.title }}
                            {{ form.title.errors }}
                        </div>

                        <!-- Rating Section -->
                        <div class="form-group">
                            <label class="font-weight-bold">Rating (1-5):</label>
                            <div class="d-flex">
                                {% for choice in form.rating.field.choices %}
                                    <div class="form-check mr-3">
                                        <input type="radio"
                                               id="id_rating_{{ forloop.counter }}"
                                               name="rating"
                                               value="{{ choice.0 }}"
                                               class="form-check-input"
                                               {% if form.rating.value == choice.0 %}checked{% endif %}>
                                        <label for="id_rating_{{ forloop.counter }}" class="form-check-label">
                                            {{ choice.1 }}
                                        </label>
                                    </div>
                                {% endfor %}
                            </div>
                              {{ form.rating.errors }}
                        </div>

                        <!-- Review Comment -->
                        <div class="form-group">
                            <label for="id_comment" class="font-weight-bold">Review Comment:</label>
                            {{ form.comment }}
                            {{ form.comment.errors }}
                        </div>

                        <button class="btn btn-dark btn-block text-uppercase mt-3">Submit Review</button>
                    </form>
                </div>
            </div>

            <!-- Product Details Section -->
            <div class="col-lg-6 mt-4 mt-lg-0">
                <div class="card p-4 shadow-sm">
                    <h4 class="text-muted">Product Details</h4>
                    <ul class="list-unstyled">
                        <li><strong>Name:</strong> {{ product.name }}</li>
                        <li><strong>Category:</strong> {{ product.category.friendly_name }}</li>
                        <li><strong>Price:</strong> ${{ product.price|floatformat:2 }}</li>
                        <li><strong>Rating:</strong> {{ product.rating|default:"No rating yet" }}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <br>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script src="{% static 'profiles/js/countryfield.js' %}"></script>
{% endblock %}

products/templates/products/delete_review.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'profiles/css/profile.css' %}">
{% endblock %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container" style="height: 65vh;">
    <div class="row">
        <div class="col">
            <hr>
            <h2 class="logo-font mb-4 text-center">Delete Review</h2>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-lg-6">
            <p class="text-muted">You are about to delete your review for <strong>{{ product.name }}</strong></p>
             <!-- Review Title -->
             <div class="form-group">
                <label for="title_id" class="font-weight-bold">Review Title:</label>
                {{ form.title }}
                {{ form.title.errors }}
            </div>
            <div class="review-details">
                <p><strong>Rating:</strong> {{review.rating }} / 5</p>
                <p><strong>Comment:</strong> {{review.comment}} </p>
            </div>
            <form method="POST" action="{% url 'delete_review' product.id review.id %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger rounded-0 text-uppercase mt-4">Delete</button>
                <a href="{% url 'user_reviews' %}" class="btn btn-secondary rounded-0 text-uppercase mt-4">Cancel</a>
            </form>
        </div>
        <div class="col-12 col-lg-6">
            <p class="text-muted">Product Details</p>
            <ul class="list-unstyled">
                <li><strong>Name:</strong> {{ product.name }}</li>
                <li><strong>Category:</strong> {{ product.category.friendly_name }}</li>
                <li><strong>Price:</strong> ${{ product.price|floatformat:2 }}</li>
                <li><strong>Rating:</strong> {{ product.rating|default:"No rating yet" }}</li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script src="{% static 'profiles/js/countryfield.js' %}"></script>
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6 ">
                <hr>
                <h2 class="logo-font mb-4"><strong>Product Managment</strong></h2>
                <h5 class="text-muted">Edit a Product</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6">
                <form method="POST" action="{% url 'edit_product' product.id %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                        {% for field in form %}
                            {% if field.name != 'image' %}
                                {{ field | as_crispy_field }}
                            {% else %}
                                {{ field }}
                            {% endif %}
                        {% endfor %}
                    <div class="text-right">
                        <a class="btn btn-outline-black rounded-0" href="{% url 'products' %}">Cancel</a>
                        <button class="btn btn-black rounded-0" type="submit">Update Product</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/edit_review.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'profiles/css/profile.css' %}">
{% endblock %}

{% block page_header %}
    <div class="container text-center py-4" style="margin-top: 25vh;">
        <h2 class="logo-font">Edit Your Review for {{ product.name }}</h2>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <!-- Review Edit Form -->
            <div class="col-lg-6">
                <div class="card p-4 shadow-sm">
                    <h4 class="text-muted">Your Review</h4>
                    <form action="{% url 'edit_review' product.id review.id %}" method="POST" id="review-form">
                        {% csrf_token %}

                         <!-- Review Title -->
                         <div class="form-group">
                            <label for="title_id" class="font-weight-bold">Review Title:</label>
                            {{ form.title }}
                            {{ form.title.errors }}
                        </div>
                        
                        <!-- Rating Selection -->
                        <div class="form-group">
                            <label class="font-weight-bold">Rating (1-5):</label>
                            <div class="d-flex flex-wrap">
                                {% for choice in form.rating.field.choices %}
                                    <div class="form-check mr-3">
                                        <input type="radio" 
                                               id="id_rating_{{ forloop.counter }}" 
                                               name="rating" 
                                               value="{{ choice.0 }}" 
                                               class="form-check-input" 
                                               {% if form.rating.value == choice.0 %}checked{% endif %}>
                                        <label for="id_rating_{{ forloop.counter }}" class="form-check-label">
                                            {{ choice.1 }}
                                        </label>
                                    </div>
                                {% endfor %}
                            </div>
                            {{ form.rating.errors }}
                        </div>

                        <!-- Review Comment -->
                        <div class="form-group">
                            <label for="id_comment" class="font-weight-bold">Review Comment:</label>
                            {{ form.comment }}
                            {{ form.comment.errors }}
                        </div>

                        <button class="btn btn-dark btn-block text-uppercase mt-3">Update Review</button>
                        <a href="{% url 'user_reviews' %}" class="btn btn-warning btn-block text-uppercase mt-3">Cancel</a>
                    </form>
                </div>
            </div>

            <!-- Product Details -->
            <div class="col-lg-6 mt-4 mt-lg-0">
                <div class="card p-4 shadow-sm">
                    <h4 class="text-muted">Product Details</h4>
                    <ul class="list-unstyled">
                        <li><strong>Name:</strong> {{ product.name }}</li>
                        <li><strong>Category:</strong> {{ product.category.friendly_name }}</li>
                        <li><strong>Price:</strong> ${{ product.price|floatformat:2 }}</li>
                        <li><strong>Rating:</strong> {{ product.rating|default:"No rating yet" }}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script src="{% static 'profiles/js/countryfield.js' %}"></script>
{% endblock %}

products/templates/products/user_reviews.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container py-4 review-container" style="margin-top: 25vh;">
    <h2 class="mb-4 text-center">My Reviews</h2>

    {% if reviews %}
        <div class="row">
            {% for review in reviews %}
                <div class="col-md-6 mb-4">
                    <div class="card shadow-sm p-3 reviews-card">
                        <h5>{{ review.product.name }}</h5>
                        <p><strong>Rating:</strong> {{ review.rating }}/5</p>
                        <p><strong>Comment:</strong><br>{{ review.comment }}</p>
                        <small class="text-muted">
                            Reviewed on {{ review.date_added|date:"F j, Y" }}
                        </small>
                        <div class="mt-3">
                            <a href="{% url 'edit_review' review.product.id review.id %}" class="btn btn-dark btn-block text-uppercase mt-3">Edit</a>
                            <a href="{% url 'delete_review' review.product.id review.id %}" class="btn btn-warning btn-block text-uppercase mt3">Delete</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p class="text-center">You haven't left any reviews yet.</p>
    {% endif %}
</div>
{% endblock %}